project:
  type: website
  output-dir: docs

website:
  title: "Blog do Rafael"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rafawsa
      - icon: twitter
        href: https://twitter.com/RafaelWSantosA1
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

