---
title: "Análise Descritiva da População com DCNT"
author: "Rafael W S Abreu"
date: "2024-10-02"
categories: [TCC, R, Stats, Econometrics]
editor_options: 
  chunk_output_type: console
---

## População com DCNT

```{r, results = 'hide', message=FALSE, echo=FALSE}
library(tidyverse) # utilizar a sintaxe tidyverse com o R
library(survey)    # análise de pesquisas complexas
library(srvyr)     # provê notação tidyverse para o pacote survey 
library(PNSIBGE)   # acesso aos dados da PNS
library(broom)     # sumariza as informações dos modelos em formato tidy
library(gt)        # tabelas
library(gtExtras)  # formatação de tabelas
```

```{r, results = 'hide', message=FALSE, echo=FALSE}
# Subgrupo de variáveis desejado:
variaveis_pns_2013 = c("C006",  # sexo
                       "C008",  # idade
                       "J007",  # possui DCNT
                       "J014",  # Usou serviço saúde nas últimas 2 semanas
                       "J037",  # Internação nos últimos 12 meses
                       "J002",  # Deixou de realizar atividades nas 2 últimas semanas por motivo de saúde
                       "J011"  # Consulta médica nos últimos 12 meses
                       )

variaveis_pns_2019 = c("C006",  # sexo
                       "C008",  # idade
                       "J007",  # possui DCNT
                       "J014",  # Usou serviço saúde nas últimas 2 semanas
                       "J037",  # Internação nos últimos 12 meses
                       "J002",  # Deixou de realizar atividades nas 2 últimas semanas por motivo de saúde
                       "J01101"  # Consulta médica nos últimos 12 meses
                       )

# lendo os dados da PNS 2013 
pns13 <-
  get_pns(
    year = 2013,
    selected = FALSE,
    anthropometry = FALSE,
    vars = variaveis_pns_2013,
    labels = TRUE,
    design = TRUE)

# Vamos utilizar a versão sem pesos dos dados para obter informações sobre __labels__ e __levels__.
df_pns13 <-
  get_pns(
    year = 2013,
    selected = FALSE,
    anthropometry = FALSE,
    vars = variaveis_pns_2013,
    labels = TRUE,
    design = FALSE)

# Vamos trabalhar com o pacote srvyr e não com o survey,
# por isso precisamos transformar survey.design2 em tbl.svy
p13 <- srvyr::as_survey(pns13)

## Ajuste dos dados para aplicar regressão de Poisson
## A regressão de Poisson requer que a variável objetivo seja numérica. 
## Neste caso vamos ajustar as variáveis categóricas para valores 0 ou 1.
levels(df_pns13$J007)
levels(df_pns13$J014)
levels(df_pns13$J037)
levels(df_pns13$J002)
levels(df_pns13$J011)
levels(df_pns13$C006)

# Vamos mudar o formato que a variável é apresentada para, no futuro, podermos realizar uma regressão de Poisson
p13 <- 
  p13 |> 
  mutate(iJ014 = if_else(J014 == "Não", 0, 1),
         iJ037 = if_else(J037 == "Não", 0, 1),
         iJ002 = if_else(J002 == "Não", 0, 1),
         cJ011 = if_else(J011 == "Nos doze últimos meses", "Sim", "Não"),
         iJ011 = if_else(J011 == "Nos doze últimos meses", 1, 0)) |> 
  mutate(J007 = relevel(J007, ref = "Não"))


```

A partir dos dados da PNS 2013 podemos identificar o percentual da população brasileira por UF portadora de DCNT.

```{r}
# Percentuais Populacionais com DCNT ----
pop_DCNT_Brasil <- 
  p13 |> 
  group_by(J007) |> 
  summarise(n_raw = unweighted(n()),
            n = survey_total()) |> 
  mutate(prop_raw = n_raw / sum(n_raw),
         prop = n / sum(n))

# tibble com o percentual Brasil:
DCNT_Brasil <- 
  tibble(
    V0001 = c("Brasil"),
    prop = c(pop_DCNT_Brasil$prop[pop_DCNT_Brasil$J007 == "Sim"])
  )

# por UF
pop_DCNT_por_uf <- 
  p13 |> 
  group_by(J007, V0001) |> 
  summarise(n = survey_total()) |> 
  mutate(prop = n / sum(n))

DCNT_por_uf <- 
  pop_DCNT_por_uf |> 
  select(J007, V0001, n) |> 
  pivot_wider(names_from = J007,
              values_from = n) |> 
  mutate(prop = Sim/(Sim + `Não`)) |> 
  select(V0001, prop)

# Fazer loliplot 13-19 ao invés da tabela abaixo! ----

# Tabela com os resultados 2013
rbind(DCNT_Brasil, DCNT_por_uf) |> 
  arrange(prop) |> 
  gt() |> 
  tab_header(title = "Percentual por região da população portadora de DCNT.",
             subtitle = "Pesquisa Nacional de Saúde, 2013.") |> 
  opt_align_table_header(align = "left") |> 
  fmt_percent(
    columns = c(prop),
    decimals = 2
  ) |> 
  cols_label(
    V0001 = md("**UF**"),
    prop = md("**População com DCNT**")
  ) |> 
  gt_highlight_rows(
    rows = V0001 == "Brasil",
    fill = "lightgrey"
  )
  
```
